### PR TITLE
updated deps

### PR DESCRIPTION
**Pull request by maikelmclauflin**
a recent vulnerability was widespread
https://npmjs.com/advisories/1179
this pr fixes updates many packages to fix that vulnerability and others

### CODE REVIEW

**Comment by maikelmclauflin** [comment]
odd. works fine when passing in the env var locally
```
OXR_APP_ID=MY_APP_ID_HERE npm t
```
is the one used in ci expired?

**Comment by kytwb** [comment]
Thank you! 🙏 I have updated the APP ID used in the CI.

**Comment by kytwb** [comment]
```
kytwb@kytwbs-mbp oxr % npm publish
npm notice 
npm notice 📦  oxr@1.1.1
npm notice === Tarball Contents === 
npm notice 1.8kB lib/cache.js   
npm notice 477B  index.js       
npm notice 3.3kB lib/Oxr.js     
npm notice 260B  lib/OxrError.js
npm notice 8.6kB test/test.js   
npm notice 787B  package.json   
npm notice 6.3kB README.md      
npm notice 127B  .travis.yml    
npm notice === Tarball Details === 
npm notice name:          oxr                                     
npm notice version:       1.1.1                                   
npm notice package size:  6.1 kB                                  
npm notice unpacked size: 21.7 kB                                 
npm notice shasum:        ec1ba548f61336e0278b56e6e93c6a122f8eaa5e
npm notice integrity:     sha512-A/ikb8ALrCDnZ[...]rOHTndp77fWCQ==
npm notice total files:   8                                       
npm notice 
+ oxr@1.1.1
```

**Comment by kytwb** [comment]
@maikelmclauflin I have also configured a cron job on Travis so the tests run weekly; I'll now have visibility if the APP ID becomes invalid again in the future.

Screen Shot 2020-03-19 at 10 15 40 PM

**Comment by maikelmclauflin** [comment]
super thanks!

**Pull request merged**
